repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        exclude: ^src/whyline/ingest/io\.py$
      - id: ruff-format
        exclude: ^src/whyline/ingest/io\.py$
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ^src/whyline/ingest/io\.py$
